# Generated by Django 4.1.1 on 2022-10-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0002_tendik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendik',
            name='fakultas',
        ),
    ]
