# Generated by Django 4.1.1 on 2022-10-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0003_remove_tendik_fakultas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tendik',
        ),
    ]
