# Generated by Django 4.1.1 on 2022-10-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0005_tendik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tendik',
            old_name='unit',
            new_name='fakultas',
        ),
    ]
