# Generated by Django 4.1.1 on 2022-10-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0006_rename_unit_tendik_fakultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tendik',
            name='prodi',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
