# Generated by Django 4.1.1 on 2022-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0008_remove_tendik_fakultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendik',
            name='prodi',
            field=models.CharField(max_length=50),
        ),
    ]
