# Generated by Django 4.1.1 on 2022-10-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0009_alter_tendik_prodi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tendik',
            name='prodi',
        ),
    ]
