# Generated by Django 4.1.1 on 2022-10-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0002_tendik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tendik',
            old_name='prodi',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='tendik',
            name='fakultas',
        ),
    ]
