# Generated by Django 4.1.1 on 2022-10-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0003_rename_prodi_tendik_unit_remove_tendik_fakultas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tendik',
            new_name='Staf',
        ),
    ]
