# Generated by Django 4.1.1 on 2022-10-05 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0004_rename_tendik_staf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staf',
            new_name='Tendik',
        ),
    ]
