# Generated by Django 4.1.1 on 2022-10-05 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0006_mahasiswa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tendik',
            new_name='staf',
        ),
    ]
