# Generated by Django 4.1.1 on 2022-10-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0007_rename_tendik_staf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staf',
            new_name='Tendik',
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
