# Generated by Django 4.1.1 on 2022-10-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0008_rename_staf_tendik_delete_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.CharField(max_length=50)),
                ('tanggal_lahir', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('fakultas', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
            ],
        ),
    ]
