# Generated by Django 4.1.1 on 2022-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pascasarjana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nip', models.CharField(max_length=50)),
                ('tanggal_lahir', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('alamat_rumah', models.CharField(max_length=50)),
            ],
        ),
    ]
